twilio:
  account_sid: AC82dae7d9261d31e9137eb7c84357cc71
  auth_token: d239beba66c9f3aa18c59257a3db384c
  trial_number: +14242950973


eureka:
  client:
    service-url:
      defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/


